services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  metrics-server:
    build: .
    container_name: metrics-server
    ports:
      - "3000:3000"
